version: "3.3"

services:
  chessbox:
    privileged: true
    image: ghcr.io/ahayden/chessbox:base
    hostname: chessbox
    environment:
      TERM: "xterm-color"
    extra_hosts:
      - "chessbox:127.0.0.1"
    container_name: chessbox
    restart: unless-stopped
    volumes:
      - type: bind
        source: /dev/serial/by-id/usb-Silicon_Labs_CP2103_USB_to_UART_Bridge_Controller_0001-if00-port0
        target: /dev/certabo
      - type: bind
        source: ./lichess.token
        target: /tmp/certabo-lichess/lichess.token
        read_only: true
      - home:/home/$USER

volumes:
  home:

